// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xzfanhhbrvtsvzhmanzr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6ZmFuaGhicnZ0c3Z6aG1hbnpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc2NTEwNzQsImV4cCI6MjA1MzIyNzA3NH0.ofhP7A22Vzylx0fcjQZDJerciQxcsuKAUY0pFXNCV4I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);