// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://huutjpaqkkggwyaunugz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1dXRqcGFxa2tnZ3d5YXVudWd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwOTU1NzEsImV4cCI6MjA3MDY3MTU3MX0.L8DkXL-TjVJJGXEcgPOyIkFazUSh77jaVw1QbUFDXvA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});